[tool.poetry]
name = "unknown-package"
version = "0.1.0"
description = ""
authors = ["TensorRT LLM [svc_tensorrt_llm@nvidia.com]"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
decord = "^0.6.0"
timm = "^1.0.19"
av = "^15.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
